FROM nginx:latest

LABEL maintainer="sortns@gmail.com"

COPY ./app/ /usr/share/nginx/html/

# RUN apk add --no-cache build-base
# RUN apk --update --upgrade add gcc musl-dev jpeg-dev zlib-dev libffi-dev cairo-dev pango-dev gdk-pixbuf-dev
# ### install dependencies:
# RUN pip3 install -r /home/app/requirements.txt

# WORKDIR /home/app
# ENTRYPOINT ["python3", "main.py"]

